id: I3AB44B19
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:26:36+00:00'
last_modified: '2022-06-08T08:32:52.828870+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17601
  title: ས་སྐྱའི་ཆོ་ག་ཁག་གཅིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0087:
      image_group_id: I1KG18090
      title: ''
      total_pages: 714
      order: 1
      base_file: 0087.txt
    4F98:
      image_group_id: I1KG18091
      title: ''
      total_pages: 512
      order: 2
      base_file: 4F98.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
