id: P009090
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17601
  title: ས་སྐྱའི་ཆོ་ག་ཁག་གཅིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    050cbc2519584dc8b59d61be4ee4895d:
      image_group_id: I1KG18090
      title: ''
      volume_number: 1
      total_pages: 714
      base_file: v001.txt
    6feb47e2a8e84cec94a87142c7f324aa:
      image_group_id: I1KG18091
      title: ''
      volume_number: 2
      total_pages: 512
      base_file: v002.txt
